/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PremiumHotel } from "./PremiumHotel";
export * as factories from "./factories";
export { PremiumHotel__factory } from "./factories/PremiumHotel__factory";
