/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace PremiumHotel {
  export type RoomStruct = {
    id: BigNumberish;
    price: BigNumberish;
    status: BigNumberish;
    occupant: AddressLike;
    bookingTime: BigNumberish;
    name: string;
    roomType: string;
    imageUrl: string;
    isActive: boolean;
  };

  export type RoomStructOutput = [
    id: bigint,
    price: bigint,
    status: bigint,
    occupant: string,
    bookingTime: bigint,
    name: string,
    roomType: string,
    imageUrl: string,
    isActive: boolean
  ] & {
    id: bigint;
    price: bigint;
    status: bigint;
    occupant: string;
    bookingTime: bigint;
    name: string;
    roomType: string;
    imageUrl: string;
    isActive: boolean;
  };
}

export interface PremiumHotelInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addReceptionist"
      | "addRoom"
      | "bookRoom"
      | "cancelReservation"
      | "checkoutRoom"
      | "confirmCheckIn"
      | "forceResetRoom"
      | "getAllRooms"
      | "getReceptionists"
      | "getRoomDetails"
      | "isReceptionist"
      | "owner"
      | "payRemaining"
      | "receptionistsList"
      | "removeReceptionist"
      | "rooms"
      | "toggleRoomActive"
      | "totalRooms"
      | "updateRoomDetails"
      | "updateRoomPrice"
      | "withdrawCustom"
      | "withdrawFunds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CheckedIn"
      | "CheckedOut"
      | "FundsWithdrawn"
      | "ReceptionistAdded"
      | "ReceptionistRemoved"
      | "RemainingPaid"
      | "ReservationCancelled"
      | "RoomAdded"
      | "RoomBooked"
      | "RoomPriceUpdated"
      | "RoomUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addReceptionist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addRoom",
    values: [BigNumberish, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "bookRoom",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelReservation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkoutRoom",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmCheckIn",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "forceResetRoom",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllRooms",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getReceptionists",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoomDetails",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isReceptionist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payRemaining",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "receptionistsList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeReceptionist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "rooms", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "toggleRoomActive",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalRooms",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateRoomDetails",
    values: [BigNumberish, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRoomPrice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawCustom",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFunds",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "addReceptionist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addRoom", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bookRoom", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelReservation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkoutRoom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmCheckIn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forceResetRoom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllRooms",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReceptionists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoomDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isReceptionist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "payRemaining",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receptionistsList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeReceptionist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rooms", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "toggleRoomActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalRooms", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateRoomDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRoomPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawCustom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFunds",
    data: BytesLike
  ): Result;
}

export namespace CheckedInEvent {
  export type InputTuple = [
    roomId: BigNumberish,
    receptionist: AddressLike,
    occupant: AddressLike
  ];
  export type OutputTuple = [
    roomId: bigint,
    receptionist: string,
    occupant: string
  ];
  export interface OutputObject {
    roomId: bigint;
    receptionist: string;
    occupant: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CheckedOutEvent {
  export type InputTuple = [roomId: BigNumberish, receptionist: AddressLike];
  export type OutputTuple = [roomId: bigint, receptionist: string];
  export interface OutputObject {
    roomId: bigint;
    receptionist: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsWithdrawnEvent {
  export type InputTuple = [
    owner: AddressLike,
    amount: BigNumberish,
    remainingContractBalance: BigNumberish
  ];
  export type OutputTuple = [
    owner: string,
    amount: bigint,
    remainingContractBalance: bigint
  ];
  export interface OutputObject {
    owner: string;
    amount: bigint;
    remainingContractBalance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReceptionistAddedEvent {
  export type InputTuple = [receptionist: AddressLike];
  export type OutputTuple = [receptionist: string];
  export interface OutputObject {
    receptionist: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReceptionistRemovedEvent {
  export type InputTuple = [receptionist: AddressLike];
  export type OutputTuple = [receptionist: string];
  export interface OutputObject {
    receptionist: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RemainingPaidEvent {
  export type InputTuple = [
    roomId: BigNumberish,
    occupant: AddressLike,
    remainingAmount: BigNumberish
  ];
  export type OutputTuple = [
    roomId: bigint,
    occupant: string,
    remainingAmount: bigint
  ];
  export interface OutputObject {
    roomId: bigint;
    occupant: string;
    remainingAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReservationCancelledEvent {
  export type InputTuple = [
    roomId: BigNumberish,
    occupant: AddressLike,
    refundAmount: BigNumberish
  ];
  export type OutputTuple = [
    roomId: bigint,
    occupant: string,
    refundAmount: bigint
  ];
  export interface OutputObject {
    roomId: bigint;
    occupant: string;
    refundAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoomAddedEvent {
  export type InputTuple = [
    roomId: BigNumberish,
    name: string,
    price: BigNumberish,
    roomType: string
  ];
  export type OutputTuple = [
    roomId: bigint,
    name: string,
    price: bigint,
    roomType: string
  ];
  export interface OutputObject {
    roomId: bigint;
    name: string;
    price: bigint;
    roomType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoomBookedEvent {
  export type InputTuple = [
    roomId: BigNumberish,
    occupant: AddressLike,
    deposit: BigNumberish
  ];
  export type OutputTuple = [roomId: bigint, occupant: string, deposit: bigint];
  export interface OutputObject {
    roomId: bigint;
    occupant: string;
    deposit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoomPriceUpdatedEvent {
  export type InputTuple = [
    roomId: BigNumberish,
    oldPrice: BigNumberish,
    newPrice: BigNumberish
  ];
  export type OutputTuple = [
    roomId: bigint,
    oldPrice: bigint,
    newPrice: bigint
  ];
  export interface OutputObject {
    roomId: bigint;
    oldPrice: bigint;
    newPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoomUpdatedEvent {
  export type InputTuple = [
    roomId: BigNumberish,
    price: BigNumberish,
    name: string,
    roomType: string,
    isActive: boolean
  ];
  export type OutputTuple = [
    roomId: bigint,
    price: bigint,
    name: string,
    roomType: string,
    isActive: boolean
  ];
  export interface OutputObject {
    roomId: bigint;
    price: bigint;
    name: string;
    roomType: string;
    isActive: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PremiumHotel extends BaseContract {
  connect(runner?: ContractRunner | null): PremiumHotel;
  waitForDeployment(): Promise<this>;

  interface: PremiumHotelInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addReceptionist: TypedContractMethod<
    [_receptionist: AddressLike],
    [void],
    "nonpayable"
  >;

  addRoom: TypedContractMethod<
    [_price: BigNumberish, _name: string, _roomType: string, _imageUrl: string],
    [void],
    "nonpayable"
  >;

  bookRoom: TypedContractMethod<[_roomId: BigNumberish], [void], "payable">;

  cancelReservation: TypedContractMethod<
    [_roomId: BigNumberish],
    [void],
    "nonpayable"
  >;

  checkoutRoom: TypedContractMethod<
    [_roomId: BigNumberish],
    [void],
    "nonpayable"
  >;

  confirmCheckIn: TypedContractMethod<
    [_roomId: BigNumberish],
    [void],
    "nonpayable"
  >;

  forceResetRoom: TypedContractMethod<
    [_roomId: BigNumberish, _refundOccupant: boolean],
    [void],
    "nonpayable"
  >;

  getAllRooms: TypedContractMethod<
    [],
    [PremiumHotel.RoomStructOutput[]],
    "view"
  >;

  getReceptionists: TypedContractMethod<[], [string[]], "view">;

  getRoomDetails: TypedContractMethod<
    [_roomId: BigNumberish],
    [PremiumHotel.RoomStructOutput],
    "view"
  >;

  isReceptionist: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  payRemaining: TypedContractMethod<[_roomId: BigNumberish], [void], "payable">;

  receptionistsList: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  removeReceptionist: TypedContractMethod<
    [_receptionist: AddressLike],
    [void],
    "nonpayable"
  >;

  rooms: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        string,
        string,
        string,
        boolean
      ] & {
        id: bigint;
        price: bigint;
        status: bigint;
        occupant: string;
        bookingTime: bigint;
        name: string;
        roomType: string;
        imageUrl: string;
        isActive: boolean;
      }
    ],
    "view"
  >;

  toggleRoomActive: TypedContractMethod<
    [_roomId: BigNumberish],
    [void],
    "nonpayable"
  >;

  totalRooms: TypedContractMethod<[], [bigint], "view">;

  updateRoomDetails: TypedContractMethod<
    [
      _roomId: BigNumberish,
      _name: string,
      _roomType: string,
      _imageUrl: string
    ],
    [void],
    "nonpayable"
  >;

  updateRoomPrice: TypedContractMethod<
    [_roomId: BigNumberish, _newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawCustom: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawFunds: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addReceptionist"
  ): TypedContractMethod<[_receptionist: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addRoom"
  ): TypedContractMethod<
    [_price: BigNumberish, _name: string, _roomType: string, _imageUrl: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "bookRoom"
  ): TypedContractMethod<[_roomId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "cancelReservation"
  ): TypedContractMethod<[_roomId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "checkoutRoom"
  ): TypedContractMethod<[_roomId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confirmCheckIn"
  ): TypedContractMethod<[_roomId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "forceResetRoom"
  ): TypedContractMethod<
    [_roomId: BigNumberish, _refundOccupant: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllRooms"
  ): TypedContractMethod<[], [PremiumHotel.RoomStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getReceptionists"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRoomDetails"
  ): TypedContractMethod<
    [_roomId: BigNumberish],
    [PremiumHotel.RoomStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isReceptionist"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payRemaining"
  ): TypedContractMethod<[_roomId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "receptionistsList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "removeReceptionist"
  ): TypedContractMethod<[_receptionist: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rooms"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        string,
        string,
        string,
        boolean
      ] & {
        id: bigint;
        price: bigint;
        status: bigint;
        occupant: string;
        bookingTime: bigint;
        name: string;
        roomType: string;
        imageUrl: string;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "toggleRoomActive"
  ): TypedContractMethod<[_roomId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalRooms"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updateRoomDetails"
  ): TypedContractMethod<
    [
      _roomId: BigNumberish,
      _name: string,
      _roomType: string,
      _imageUrl: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateRoomPrice"
  ): TypedContractMethod<
    [_roomId: BigNumberish, _newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawCustom"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawFunds"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "CheckedIn"
  ): TypedContractEvent<
    CheckedInEvent.InputTuple,
    CheckedInEvent.OutputTuple,
    CheckedInEvent.OutputObject
  >;
  getEvent(
    key: "CheckedOut"
  ): TypedContractEvent<
    CheckedOutEvent.InputTuple,
    CheckedOutEvent.OutputTuple,
    CheckedOutEvent.OutputObject
  >;
  getEvent(
    key: "FundsWithdrawn"
  ): TypedContractEvent<
    FundsWithdrawnEvent.InputTuple,
    FundsWithdrawnEvent.OutputTuple,
    FundsWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "ReceptionistAdded"
  ): TypedContractEvent<
    ReceptionistAddedEvent.InputTuple,
    ReceptionistAddedEvent.OutputTuple,
    ReceptionistAddedEvent.OutputObject
  >;
  getEvent(
    key: "ReceptionistRemoved"
  ): TypedContractEvent<
    ReceptionistRemovedEvent.InputTuple,
    ReceptionistRemovedEvent.OutputTuple,
    ReceptionistRemovedEvent.OutputObject
  >;
  getEvent(
    key: "RemainingPaid"
  ): TypedContractEvent<
    RemainingPaidEvent.InputTuple,
    RemainingPaidEvent.OutputTuple,
    RemainingPaidEvent.OutputObject
  >;
  getEvent(
    key: "ReservationCancelled"
  ): TypedContractEvent<
    ReservationCancelledEvent.InputTuple,
    ReservationCancelledEvent.OutputTuple,
    ReservationCancelledEvent.OutputObject
  >;
  getEvent(
    key: "RoomAdded"
  ): TypedContractEvent<
    RoomAddedEvent.InputTuple,
    RoomAddedEvent.OutputTuple,
    RoomAddedEvent.OutputObject
  >;
  getEvent(
    key: "RoomBooked"
  ): TypedContractEvent<
    RoomBookedEvent.InputTuple,
    RoomBookedEvent.OutputTuple,
    RoomBookedEvent.OutputObject
  >;
  getEvent(
    key: "RoomPriceUpdated"
  ): TypedContractEvent<
    RoomPriceUpdatedEvent.InputTuple,
    RoomPriceUpdatedEvent.OutputTuple,
    RoomPriceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RoomUpdated"
  ): TypedContractEvent<
    RoomUpdatedEvent.InputTuple,
    RoomUpdatedEvent.OutputTuple,
    RoomUpdatedEvent.OutputObject
  >;

  filters: {
    "CheckedIn(uint256,address,address)": TypedContractEvent<
      CheckedInEvent.InputTuple,
      CheckedInEvent.OutputTuple,
      CheckedInEvent.OutputObject
    >;
    CheckedIn: TypedContractEvent<
      CheckedInEvent.InputTuple,
      CheckedInEvent.OutputTuple,
      CheckedInEvent.OutputObject
    >;

    "CheckedOut(uint256,address)": TypedContractEvent<
      CheckedOutEvent.InputTuple,
      CheckedOutEvent.OutputTuple,
      CheckedOutEvent.OutputObject
    >;
    CheckedOut: TypedContractEvent<
      CheckedOutEvent.InputTuple,
      CheckedOutEvent.OutputTuple,
      CheckedOutEvent.OutputObject
    >;

    "FundsWithdrawn(address,uint256,uint256)": TypedContractEvent<
      FundsWithdrawnEvent.InputTuple,
      FundsWithdrawnEvent.OutputTuple,
      FundsWithdrawnEvent.OutputObject
    >;
    FundsWithdrawn: TypedContractEvent<
      FundsWithdrawnEvent.InputTuple,
      FundsWithdrawnEvent.OutputTuple,
      FundsWithdrawnEvent.OutputObject
    >;

    "ReceptionistAdded(address)": TypedContractEvent<
      ReceptionistAddedEvent.InputTuple,
      ReceptionistAddedEvent.OutputTuple,
      ReceptionistAddedEvent.OutputObject
    >;
    ReceptionistAdded: TypedContractEvent<
      ReceptionistAddedEvent.InputTuple,
      ReceptionistAddedEvent.OutputTuple,
      ReceptionistAddedEvent.OutputObject
    >;

    "ReceptionistRemoved(address)": TypedContractEvent<
      ReceptionistRemovedEvent.InputTuple,
      ReceptionistRemovedEvent.OutputTuple,
      ReceptionistRemovedEvent.OutputObject
    >;
    ReceptionistRemoved: TypedContractEvent<
      ReceptionistRemovedEvent.InputTuple,
      ReceptionistRemovedEvent.OutputTuple,
      ReceptionistRemovedEvent.OutputObject
    >;

    "RemainingPaid(uint256,address,uint256)": TypedContractEvent<
      RemainingPaidEvent.InputTuple,
      RemainingPaidEvent.OutputTuple,
      RemainingPaidEvent.OutputObject
    >;
    RemainingPaid: TypedContractEvent<
      RemainingPaidEvent.InputTuple,
      RemainingPaidEvent.OutputTuple,
      RemainingPaidEvent.OutputObject
    >;

    "ReservationCancelled(uint256,address,uint256)": TypedContractEvent<
      ReservationCancelledEvent.InputTuple,
      ReservationCancelledEvent.OutputTuple,
      ReservationCancelledEvent.OutputObject
    >;
    ReservationCancelled: TypedContractEvent<
      ReservationCancelledEvent.InputTuple,
      ReservationCancelledEvent.OutputTuple,
      ReservationCancelledEvent.OutputObject
    >;

    "RoomAdded(uint256,string,uint256,string)": TypedContractEvent<
      RoomAddedEvent.InputTuple,
      RoomAddedEvent.OutputTuple,
      RoomAddedEvent.OutputObject
    >;
    RoomAdded: TypedContractEvent<
      RoomAddedEvent.InputTuple,
      RoomAddedEvent.OutputTuple,
      RoomAddedEvent.OutputObject
    >;

    "RoomBooked(uint256,address,uint256)": TypedContractEvent<
      RoomBookedEvent.InputTuple,
      RoomBookedEvent.OutputTuple,
      RoomBookedEvent.OutputObject
    >;
    RoomBooked: TypedContractEvent<
      RoomBookedEvent.InputTuple,
      RoomBookedEvent.OutputTuple,
      RoomBookedEvent.OutputObject
    >;

    "RoomPriceUpdated(uint256,uint256,uint256)": TypedContractEvent<
      RoomPriceUpdatedEvent.InputTuple,
      RoomPriceUpdatedEvent.OutputTuple,
      RoomPriceUpdatedEvent.OutputObject
    >;
    RoomPriceUpdated: TypedContractEvent<
      RoomPriceUpdatedEvent.InputTuple,
      RoomPriceUpdatedEvent.OutputTuple,
      RoomPriceUpdatedEvent.OutputObject
    >;

    "RoomUpdated(uint256,uint256,string,string,bool)": TypedContractEvent<
      RoomUpdatedEvent.InputTuple,
      RoomUpdatedEvent.OutputTuple,
      RoomUpdatedEvent.OutputObject
    >;
    RoomUpdated: TypedContractEvent<
      RoomUpdatedEvent.InputTuple,
      RoomUpdatedEvent.OutputTuple,
      RoomUpdatedEvent.OutputObject
    >;
  };
}
