/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace PremiumHotel {
  export type RoomStruct = {
    id: BigNumberish;
    price: BigNumberish;
    status: BigNumberish;
    occupant: AddressLike;
    bookingTime: BigNumberish;
  };

  export type RoomStructOutput = [
    id: bigint,
    price: bigint,
    status: bigint,
    occupant: string,
    bookingTime: bigint
  ] & {
    id: bigint;
    price: bigint;
    status: bigint;
    occupant: string;
    bookingTime: bigint;
  };
}

export interface PremiumHotelInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "bookRoom"
      | "cancelReservation"
      | "checkoutRoom"
      | "confirmCheckIn"
      | "getAllRooms"
      | "getRoomDetails"
      | "owner"
      | "payRemaining"
      | "receptionist"
      | "rooms"
      | "setReceptionist"
      | "totalRooms"
      | "withdrawFunds"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "bookRoom",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelReservation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkoutRoom",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmCheckIn",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllRooms",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoomDetails",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payRemaining",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "receptionist",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "rooms", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "setReceptionist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalRooms",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFunds",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "bookRoom", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelReservation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkoutRoom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmCheckIn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllRooms",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoomDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "payRemaining",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receptionist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rooms", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setReceptionist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalRooms", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFunds",
    data: BytesLike
  ): Result;
}

export interface PremiumHotel extends BaseContract {
  connect(runner?: ContractRunner | null): PremiumHotel;
  waitForDeployment(): Promise<this>;

  interface: PremiumHotelInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bookRoom: TypedContractMethod<[_roomId: BigNumberish], [void], "payable">;

  cancelReservation: TypedContractMethod<
    [_roomId: BigNumberish],
    [void],
    "nonpayable"
  >;

  checkoutRoom: TypedContractMethod<
    [_roomId: BigNumberish],
    [void],
    "nonpayable"
  >;

  confirmCheckIn: TypedContractMethod<
    [_roomId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAllRooms: TypedContractMethod<
    [],
    [PremiumHotel.RoomStructOutput[]],
    "view"
  >;

  getRoomDetails: TypedContractMethod<
    [_roomId: BigNumberish],
    [PremiumHotel.RoomStructOutput],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  payRemaining: TypedContractMethod<[_roomId: BigNumberish], [void], "payable">;

  receptionist: TypedContractMethod<[], [string], "view">;

  rooms: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, string, bigint] & {
        id: bigint;
        price: bigint;
        status: bigint;
        occupant: string;
        bookingTime: bigint;
      }
    ],
    "view"
  >;

  setReceptionist: TypedContractMethod<
    [_receptionist: AddressLike],
    [void],
    "nonpayable"
  >;

  totalRooms: TypedContractMethod<[], [bigint], "view">;

  withdrawFunds: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bookRoom"
  ): TypedContractMethod<[_roomId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "cancelReservation"
  ): TypedContractMethod<[_roomId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "checkoutRoom"
  ): TypedContractMethod<[_roomId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confirmCheckIn"
  ): TypedContractMethod<[_roomId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAllRooms"
  ): TypedContractMethod<[], [PremiumHotel.RoomStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getRoomDetails"
  ): TypedContractMethod<
    [_roomId: BigNumberish],
    [PremiumHotel.RoomStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payRemaining"
  ): TypedContractMethod<[_roomId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "receptionist"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rooms"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, string, bigint] & {
        id: bigint;
        price: bigint;
        status: bigint;
        occupant: string;
        bookingTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setReceptionist"
  ): TypedContractMethod<[_receptionist: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalRooms"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawFunds"
  ): TypedContractMethod<[], [void], "nonpayable">;

  filters: {};
}
